#!/bin/bash
set -a

mkdir -p build/log

LOG=$PWD/build/log/httpcore.log
SERVER_PORT=9090
WS_URL="http://localhost:${SERVER_PORT}"

start_server() {
  pushd test/httpcore >/dev/null
    
  printf 'getting set up' 1>&2
  ./gradlew run --args "${SERVER_PORT}"   &> $LOG &

  JVM_PID=$!
  while [ -z "$(curl -sI ${WS_URL} | grep 'HTTP/1.1 200')" ]; do
    if ! kill -0 "${JVM_PID}" 2> /dev/null; then
      printf '. failed!\n\nprocess exited unexpectedly:\n'
      cat $LOG
      exit 1
    fi

    printf '.' 1>&2
    sleep 1
  done
  printf ' ok\n\n' 1>&2
  popd
}
start_server

run_bats() {
  bats --tap test/httpcore/httpcore.bats
}
${@:-run_bats}
bats_ret=$?

kill $JVM_PID
wait $JVM_PID

exit $bats_ret
