#!/bin/bash
set -x

LOG=/run/petclinic.log
java -ea -Dappmap.debug -javaagent:/appmap.jar -jar /petclinic.jar &> $LOG &
JVM_PID=$!

export WS_URL="http://localhost:8080"

printf 'getting set up'
while [ -z "$(curl -sI "${WS_URL}" | grep 'HTTP/1.1 200')" ]; do
  if ! kill -0 "${JVM_PID}" 2> /dev/null; then
    printf '. failed!\n\nprocess exited unexpectedly:\n'
    cat $LOG
    exit 1
  fi

  printf '.'
  sleep 1
done
printf ' ok\n\n'

${@:-bats --tap /test/*.bats}
bats_ret=$?

kill ${JVM_PID}
wait -f ${JVM_PID}
cat $LOG
exit $bats_ret
