plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@google/semantic-release-replace-plugin'
    - replacements:
        - files: [build.gradle]
          from: (?<=def\s+defaultVersion\s*=\s*').*(?<!')
          to: ${nextRelease.version}
          countMatches: true
          results:
            - file: build.gradle
              hasChanged: true
              numMatches: 1
              numReplacements: 1
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - build.gradle
  - - '@semantic-release/exec'
    #- publishCmd: ./gradlew publish
    #- publishCmd: ./gradlew publishToSonatype closeSonatypeStagingRepository
    - publishCmd: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
  - - '@semantic-release/github'
    - assets:
        - build/libs/appmap-*.jar*
