/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.appland.appmap.record;

import javassist.ClassPool;
import javassist.CtClass;
import javassist.CtMethod;
import javassist.NotFoundException;

import static org.junit.Assert.fail;

import java.util.ArrayList;

import org.junit.Test;

public class EventFactoryTest {
  @Test
  public void testRegister() {
    ArrayList<CtMethod> behaviorsToRegister = new ArrayList<CtMethod>();

    try {
      ClassPool classPool = ClassPool.getDefault();
      CtClass classType = classPool.get("com.appland.appmap.ExampleClass");

      behaviorsToRegister.add(classType.getDeclaredMethod("methodStaticZeroParam"));
      behaviorsToRegister.add(classType.getDeclaredMethod("methodStaticSingleParam"));
      behaviorsToRegister.add(classType.getDeclaredMethod("methodZeroParam"));
      behaviorsToRegister.add(classType.getDeclaredMethod("methodOneParam"));
    } catch (NotFoundException e) {
      fail(e.getMessage());
    }

    for (CtMethod method : behaviorsToRegister) {
      EventFactory.get().register(method);
    }
  }
}
