#!/bin/bash

rsync -au --delete build/fixtures/spring-petclinic test/junit
cp test/petclinic/appmap.yml test/junit/spring-petclinic
cp test/junit/pom.xml test/junit/spring-petclinic/

project_dir=$(pwd)
cd test/junit/spring-petclinic
./mvnw test
cd "$project_dir"

mkdir -p build/log

run_bats() {
  bats --tap test/junit/junit.bats > build/log/bats-junit.log 2>&1
}
${@:-run_bats}
bats_ret=$?

cat build/log/bats-junit.log
exit $bats_ret
