#!/bin/bash

rm -rf agent_cli/spring-petclinic
tar -C build/fixtures -c -f - ./spring-petclinic | tar -x -f - -C test/agent_cli
cp test/petclinic/appmap.yml test/agent_cli/spring-petclinic/.

mkdir -p build/log

run_bats() {
  bats --tap test/agent_cli/agent_cli.bats
}
${@:-run_bats}
bats_ret=$?

exit $bats_ret
