/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.appland.appmap;

import org.junit.Test;

public class AppTest {
  @Test
  public void testAppHasAGreeting() {
    SayHello classUnderTest = new SayHello();
    classUnderTest.hello();
  }
}
